Misc.
git-svn-id: file:///home/darshan/svn-tmp-repo/translationhelper@308 615dbf4c-cc44-46bf-a361-beab69ac16e6

diff --git a/restart b/restart
--- a/restart
+++ b/restart
@@ -1,10 +1,15 @@
 #!/bin/bash
 
-./stop
+PID_FILE='./run/pid'
 
-if [ "$?" -ne 0 ]
+if [ ! -e $PID_FILE ]
 then
-    echo "$0: could not stop your app; starting a new one anyway"
+    echo "Error: $PID_FILE does not exist"
+    exit 1
 fi
 
-./start
+servers=`wc $PID_FILE | awk '{print $1;}'`
+
+./stop
+
+./start $servers
